name: 'MOxUnit'
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: joergbrech/moxunit-action@master
        with:
          tests: matlab/test
          src: matlab
